node_id=0
nr_nodes=4
block_size=4096
local_region_size=67108864
enable_rdma=0
enable_cache=1
enable_write_batching=1
rdma_enable_control_path=1
cache_admission_policy=always
coherence_mode_override=adaptive
profiling_window_size=8
remote_write_batch_threshold=2
adaptive_mode_batch_threshold=1
